name: Package

on: push

jobs:
  server:
    name: StudioPresence App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0

      - name: Install and Package Server
        run: |
          pnpm install --frozen-lockfile
          pnpm run package:server

      - name: Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: StudioPresence-Windows
          path: |
            release/studiopresence-win*.exe
            release/startup.vbs

      - name: MacOS Release
        uses: actions/upload-artifact@v4
        with:
          name: StudioPresence-macOS
          path: release/studiopresence-macos*

      - name: Linux Release
        uses: actions/upload-artifact@v4
        with:
          name: StudioPresence-Linux
          path: release/studiopresence-linux*

  client:
    name: StudioPresence Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.10.0

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and Package Client
        run: |
          mkdir release
          pnpm install --frozen-lockfile
          pnpm build:client

      - name: Upload plugin
        uses: actions/upload-artifact@v4
        with:
          name: StudioPresence-Plugin
          path: release/studiopresence*.rbxm
